// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using the_fitness_assistant.Data;

#nullable disable

namespace thefitnessassistant.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("the_fitness_assistant.Models.CalorieGoal", b =>
                {
                    b.Property<int>("CalorieGoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CalorieGoalId"));

                    b.Property<int>("DailyCalories")
                        .HasColumnType("integer");

                    b.Property<string>("GoalType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("CalorieGoalId");

                    b.HasIndex("UserId");

                    b.ToTable("CalorieGoals");
                });

            modelBuilder.Entity("the_fitness_assistant.Models.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FoodId"));

                    b.Property<int>("Calories")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServingSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FoodId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("the_fitness_assistant.Models.FoodLogEntry", b =>
                {
                    b.Property<int>("FoodLogEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FoodLogEntryId"));

                    b.Property<int>("FoodId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Servings")
                        .HasColumnType("double precision");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("FoodLogEntryId");

                    b.HasIndex("FoodId");

                    b.HasIndex("UserId");

                    b.ToTable("FoodLogEntries");
                });

            modelBuilder.Entity("the_fitness_assistant.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("the_fitness_assistant.Models.CalorieGoal", b =>
                {
                    b.HasOne("the_fitness_assistant.Models.User", "User")
                        .WithMany("CalorieGoals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("the_fitness_assistant.Models.Food", b =>
                {
                    b.HasOne("the_fitness_assistant.Models.User", "CreatedByUser")
                        .WithMany("Foods")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("the_fitness_assistant.Models.FoodLogEntry", b =>
                {
                    b.HasOne("the_fitness_assistant.Models.Food", "Food")
                        .WithMany("FoodLogEntries")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("the_fitness_assistant.Models.User", "User")
                        .WithMany("FoodLogEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("User");
                });

            modelBuilder.Entity("the_fitness_assistant.Models.Food", b =>
                {
                    b.Navigation("FoodLogEntries");
                });

            modelBuilder.Entity("the_fitness_assistant.Models.User", b =>
                {
                    b.Navigation("CalorieGoals");

                    b.Navigation("FoodLogEntries");

                    b.Navigation("Foods");
                });
#pragma warning restore 612, 618
        }
    }
}
